### ISSUE TITLE
Name of npm package differs from repository name.

### ISSUE THREAD

**Issue by wgrabowski** [matewka/uglicssy-preset-angular#3]
In npm this package is published as uglicssy-angular.
That's different name than used in all documentation for [uglicssy](https://github.com/matewka/uglicssy) ecosystem and it is confusing.
Please be consistent.

**Comment by matewka** [comment]
Uglicssy-angular npm package is now deprecated.
The package.json for this repository has been updated.
I've added a new npm package called [uglicssy-preset-angular](https://www.npmjs.com/package/uglicssy-preset-angular).
